# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
a = np.array([0,1,2,3,4,5,6,7,8,9])
a = a.reshape(2,5)

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
a= np.array([[0,1,2,3,4],[5,6,7,8,9]])
b= np.array([[1,1,1,1,1],[1,1,1,1,1]])
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
a= np.array([[0,1,2,3,4],[5,6,7,8,9]])
b= np.array([[1,1,1,1,1],[1,1,1,1,1]])
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
a = np.array([[0,1,2,3,4],[5,6,7,8,9]])
a = a.flatten()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [5]:
b = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])
b = b.flatten()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [6]:
c = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
c = c.reshape(5,3)

## Question:7

### Create 5x5 an array and find the square of an array?

In [7]:
f = np.arange(25).reshape(5,5)
np.square(a)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

## Question:8

### Create 5x6 an array and find the mean?

In [8]:
g = np.arange(30).reshape(5,6)
g.mean()

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [9]:
g.std()

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [10]:
np.median(g)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [11]:
np.transpose(g)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [12]:
h = np.arange(16).reshape(4,4)
np.diag(h).sum()

30

## Question:13

### Find the determinant of the previous array in Q12?

In [13]:
np.linalg.det(h)

-2.9582283945787796e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [14]:
a = np.random.randn(100)
print(np.percentile(a,5))
print(np.percentile(a,95))

-1.5788479144998746
1.7907406398604766


## Question:15

### How to find if a given array has any null values?

In [1]:
n = np.zeros(10)
np.any(n==0)

NameError: name 'np' is not defined